name: Build TypeScript Project

on:
  push:
    branches:
      - "**"  # Runs on push to all branches
  pull_request:
    branches:
      - main  # Runs on pull request to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.16'  # Use the same Node.js version as locally

      - name: Install dependencies
        run: npm ci  # Use 'npm ci' for a clean install based on package-lock.json

      - name: Verify files generated before build
        run: |
          echo "Checking generated files..."
          # You can add custom commands here to verify files existence
          ls -al ./src/ # Check if all necessary files are in place

      # Optional: If there's a step that generates files needed for the TypeScript build
      # - name: Generate necessary files
      #   run: npm run generate-files  # Example script to generate Modal.js, etc.

      - name: Compile TypeScript
        run: npx tsc  # Compiles TypeScript based on tsconfig.json

      - name: Verify TypeScript output
        run: ls -al ./dist/  # List files in the output directory to ensure expected output

      - name: Bundle with Webpack
        run: npm run build:webpack  # Assuming your build script uses Webpack
